services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}

    image: ghcr.io/abcdotaom-thaicom/gip-dev-cpu-base:v1.0.2
    container_name: gip-dev-${USER}
    # user: "${UID}:${GID}"
    working_dir: /workspaces
    environment:
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
    volumes:
      - .:/workspaces
      - /home/${USER}:/home/${USER}
      - ~/.ssh:/home/${USER}/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /fs5/anawat/sen2cog_poc:/workspaces/data
    command: bash -l
    stdin_open: true
    tty: true
