services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}
    image: ghcr.io/abcdotaom-thaicom/gip-dev-gpu-base:v1.0.2
    container_name: gip-dev-gpu-${USER}
    # user: "${UID}:${GID}"
    working_dir: /workspaces
    environment:
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
    volumes:
      - .:/workspaces
      - /home/${USER}:/home/${USER}
      - ~/.ssh:/home/${USER}/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -l
    stdin_open: true
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
