services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}

    image: ghcr.io/abcdotaom-thaicom/gip-dev-cpu-base:v1.0.1
    container_name: gip-dev-${USER}
    user: "${UID}:${GID}"
    working_dir: /workspaces
    volumes:
      - .:/workspaces
      - ~/.ssh:/home/${USER}/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -l
    stdin_open: true
    tty: true
