version: '3.10'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: tensorflow/tensorflow:2.15.0-gpu
    image: gip-devcontainer-template
    container_name: gip-dev
    working_dir: /workspaces
    volumes:
      - .:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -l
    runtime: nvidia  # ✅ สำหรับ Docker ที่ยังรองรับ runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
