version: '3.10'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    image: gip-devcontainer-template
    container_name: gip-dev
    working_dir: /workspaces
    volumes:
      - .:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -l
