name: Build and Push to GHCR

on:
  push:
    tags:
      - 'v*.*.*-cpu'
      - 'v*.*.*-gpu'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name
        run: |
          if [[ "${GITHUB_REF_NAME}" == *-gpu ]]; then
            echo "IMAGE_NAME=ghcr.io/thaicomplc/gip-dev-gpu-base" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=ghcr.io/thaicomplc/gip-dev-cpu-base" >> $GITHUB_ENV
          fi
          echo "TAG=${GITHUB_REF_NAME%%-*}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
